name: dady_jokes_app
description: An app that displays dady jokes with some personalization options

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ^3.0.4

dependencies:
  flutter:
    sdk: flutter

  # General state management
  get: 4.6.5

  # HTTP Requests
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1

  # Data
  json_annotation: ^4.5.0
  copy_with_extension: ^4.0.0

  # UI
  cupertino_icons: ^1.0.2

dependency_overrides:
  xml: 6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Env
  flutter_flavorizr: ^2.1.3

  # Lint
  flutter_lints: ^2.0.0
  analyzer: ^3.1.0

  # Data
  build_runner: ^2.0.4
  json_serializable: ^6.1.4
  copy_with_extension_gen: ^4.0.0

  # Tests
  mockito: ^5.0.10
  http_mock_adapter: ^0.3.2

  # UI
  flutter_launcher_icons: "^0.9.2"
  flutter_native_splash: ^2.2.4

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:
  ide: idea

  instructions:
    - assets:download
    - assets:extract
    - android:androidManifest
    - android:buildGradle
    - flutter:flavors
    - flutter:app
    - flutter:targets
    - ios:xcconfig
    - ios:buildTargets
    - ios:schema
    - ios:plist
    - assets:clean
    - ide:config

  flavors:
    dev:
      app:
        name: "[Dev]Dady Jokes"
      android:
        applicationId: "com.dvosoftware.dadyjokes.dev"
      ios:
        bundleId: "com.dvosoftware.dadyjokes.dev"
        variables:
          APPLINK_SCHEME:
            value: "dadyjokesappdev"

    qa:
      app:
        name: "[QA]Dady Jokes"
      android:
        applicationId: "com.dvosoftware.dadyjokes.qa"
      ios:
        bundleId: "com.dvosoftware.dadyjokes.qa"
        variables:
          APPLINK_SCHEME:
            value: "dadyjokesappqa"

    staging:
      app:
        name: "[Stg]Dady Jokes"
      android:
        applicationId: "com.dvosoftware.dadyjokes.staging"
      ios:
        bundleId: "com.dvosoftware.dadyjokes.staging"
        variables:
          APPLINK_SCHEME:
            value: "dadyjokesappstg"

    prod:
      app:
        name: "Dady Jokes"
      android:
        applicationId: "com.dvosoftware.dadyjokes"
      ios:
        bundleId: "com.dvosoftware.dadyjokes"
        variables:
          APPLINK_SCHEME:
            value: "dadyjokesapp"

flutter_icons:
  image_path_android: "assets/launcher/ic_launcher.png"
  image_path_ios: "assets/launcher/ic_launcher_ios.png"
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/launcher/ic_launcher_adaptive_fore.png"
  remove_alpha_ios: true