// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMCA3NechQXAdNnxejmVUxCYVHmtZ9Kco',
    appId: '1:1023167023864:web:8ae470b80f9cadd05b890d',
    messagingSenderId: '1023167023864',
    projectId: 'dady-jokes-dev',
    authDomain: 'dady-jokes-dev.firebaseapp.com',
    storageBucket: 'dady-jokes-dev.appspot.com',
    measurementId: 'G-FBQW1S5VQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC71u3eWxYwDEqafn_-rOh4twktuahpg_0',
    appId: '1:1023167023864:android:c8a7e7b0d24a3f3f5b890d',
    messagingSenderId: '1023167023864',
    projectId: 'dady-jokes-dev',
    storageBucket: 'dady-jokes-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxduGySjy5NlyVY44L7CAYZRaSch_OPUE',
    appId: '1:1023167023864:ios:83e80a155c2cd8035b890d',
    messagingSenderId: '1023167023864',
    projectId: 'dady-jokes-dev',
    storageBucket: 'dady-jokes-dev.appspot.com',
    iosClientId: '1023167023864-043u6gdj6o2ii56mvgbns6693i2mdafb.apps.googleusercontent.com',
    iosBundleId: 'com.dvosoftware.dadyjokes.dev',
  );
}
